[package]
name = "bvh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath="*"
rand="*"
image="*"
vk_utils={git = "https://github.com/DannyvanSwieten/vk_utils.git"}