[package]
name = "tracey_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libraytracer = { path = "../libraytracer" }
noise = "*"
image = "*"
rand = "*"
nalgebra-glm = "*"
tobj = "*"
