#version 460

struct Ray
{
    vec3 origin;
    vec3 direction;
    vec3 invDirection;
};

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(std430, set = 0, binding = 0) writeonly buffer RayBuffer {
    Ray rays[];
};

Ray generate_ray(vec2 pixel, vec2 resolution);

void main()
{
    uint i = gl_GlobalInvocationID.y * 720 + gl_GlobalInvocationID.x;
    rays[i] = generate_ray(gl_GlobalInvocationID.xy, gl_NumWorkGroups.xy);
}

